#!/usr/bin/env bash

alias docko=docker-compose

alias docko-run='docko run --rm web'
alias docko-exec='docko-run bundle exec'
alias docko-rails='docko-exec rails'
alias docko-rake='docko-exec rake'
alias docko-debug='docko run --rm --service-ports web'
alias docko-logs='docko logs --tail 500 -f'
function ___docko-psql {
  docko run --rm db psql -h db $1 postgres
}

alias docko-psql='___docko-psql'

alias ddvc='docker volume rm $(docker volume ls -q -f dangling=true)'
