#!bash

[[ -f $HOME/.custom-bash/git-completion ]] && source $HOME/.custom-bash/git-completion

alias g='git'
alias g{='git stash'
alias g}='git stash apply'
alias glg='git log'
complete -o default -o nospace -F _git_log glg
alias gdc='git diff --cached'
complete -o default -o nospace -F _git_diff gdc
alias gcm='git commit -m'
alias gc="git commit"
alias gca='git commit -a'
alias gcam='git commit -a -m'
alias gs='git status'
alias gst='git status'
alias gco="git checkout"
alias gpp="git pull && git push"
complete -o default -o nospace -F _git_checkout gco
alias gpul="git pull"
complete -o default -o nospace -F _git_pull gpull
alias gpsh="git push"
complete -o default -o nospace -F _git_push gpush
alias gd="git diff"
complete -o default -o nospace -F _git_diff gd
alias gbr="git branch"
complete -o default -o nospace -F _git_branch gbr
alias ga="git add"
complete -o default -o nospace -F _git_add ga

alias git-nuclear-option="git reset --hard; git clean -xdf"
alias gno="git-nuclear-option"

FG_BLACK="\[\033[01;30m\]"
FG_WHITE="\[\033[01;37m\]"
FG_RED="\[\033[01;31m\]"
FG_GREEN="\[\033[01;32m\]"
FG_BLUE="\[\033[01;34m\]"
NO_COLOR="\[\e[0m\]"

#build PS1
#don't set PS1 for dumb terminals
if [[ "$TERM" != 'dumb' ]] && [[ -n "$BASH" ]]; then
    PS1=''
    #don't modify titlebar on console
    [[ "$TERM" != 'linux' && "$CF_REAL_TERM" != "eterm-color" ]] && PS1="${PS1}\[\e]2;\u@\H:\W\a"

    #use a red $ if you're root, white otherwise
    #if [[ $WHOAMI = "root" ]]; then
    #	  #red hostname
	#      PS1="${PS1}${FG_RED}"
    #else
      	#green user@hostname
     #	  PS1="${PS1}${FG_GREEN}"
    #fi
 
    GIT_PS1_SHOWDIRTYSTATE=1
    #working dir basename and prompt
    PS1="${PS1}${FG_BLUE}\W${FG_RED}\$(__git_ps1 "[%s]")${FG_BLUE}\$ ${NO_COLOR}"
fi

git config --global color.ui auto


